name: CI

on:
  workflow_dispatch:
  push:

jobs:
  make-debug:
    runs-on: macos-latest
    steps:
      - name: Checkout code and all tags
        uses: actions/checkout@v4
        with:
          # Why not just "fetch-tags: 1"?
          # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
          fetch-depth: 0
          filter: tree:0

      - name: Run "make debug"
        run: make debug

  make-release-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code and all tags
        uses: actions/checkout@v4
        with:
          # Why not just "fetch-tags: 1"?
          # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
          fetch-depth: 0
          filter: tree:0

      - name: Run "make release-build"
        uses: ./.github/actions/make-release-build
        with:
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASS: ${{ secrets.CERT_PASS }}
          TEAM_ID: ${{ vars.TEAM_ID }}
